/*
 * CREATE SYSTEM DATABASE.
 */
IF (NOT EXISTS(SELECT 1 FROM master.dbo.sysdatabases WHERE NAME = N'COMP229_TEAMASSIGN'))
BEGIN
	CREATE DATABASE COMP229_TEAMASSIGN
END

USE Comp229_TeamAssign
GO

/*
 * CREATE SYSTEM TABLES.
 */
IF (NOT EXISTS(SELECT 1 FROM dbo.sysobjects WHERE ID = OBJECT_ID(N'dbo.TBUB_PUBLISHERS') AND OBJECTPROPERTY(ID, N'IsTable') = 1))
BEGIN
	CREATE TABLE TBUB_PUBLISHERS (
		PUBLISHER_ID
			DECIMAL(6, 0)
			PRIMARY KEY
			CLUSTERED
			NOT NULL
			IDENTITY
	,	PUBLISHER_NAME
			VARCHAR(64)
			NOT NULL
	)
END

IF (NOT EXISTS(SELECT 1 FROM dbo.sysobjects WHERE ID = OBJECT_ID(N'dbo.TBUB_AUTHORS') AND OBJECTPROPERTY(ID, N'IsTable') = 1))
BEGIN
	CREATE TABLE TBUB_AUTHORS (
		AUTHOR_ID
			DECIMAL(10, 0)
			PRIMARY KEY
			CLUSTERED
			NOT NULL
			IDENTITY
	,	AUTHOR_NAME
			VARCHAR(128)
			NOT NULL
	)
END

IF (NOT EXISTS(SELECT 1 FROM dbo.sysobjects WHERE ID = OBJECT_ID(N'dbo.TBUB_BOOKS') AND OBJECTPROPERTY(ID, N'IsTable') = 1))
BEGIN
	CREATE TABLE TBUB_BOOKS (
		BOOK_ISBN
			DECIMAL(13, 0)
			PRIMARY KEY
			CLUSTERED
			NOT NULL
	,	BOOK_TITLE
			VARCHAR(128)
			NOT NULL
	,	BOOK_DESCRIPTION
			VARCHAR(512)
	,	BOOK_PUBLICATION_DATE
			DATE
			NOT NULL
	,	BOOK_EDITION
			DECIMAL(2, 0)
			NOT NULL
	,	BOOK_IS_AVAILABLE
			BIT
			NOT NULL
	,	BOOK_QUANTITY_AVAILABLE
			DECIMAL(3, 0)
			NOT NULL
	,	BOOK_IMG_URL_01
			VARCHAR(255)
			NOT NULL
	,	BOOK_IMG_URL_02
			VARCHAR(255)
	,	BOOK_IMG_URL_03
			VARCHAR(255)
	,	BOOK_IMG_URL_04
			VARCHAR(255)
	,	BOOK_IMG_URL_05
			VARCHAR(255)
	,	BOOK_CREATE_DATE
			DATETIME
			NOT NULL
	,	BOOK_REMOVE_DATE
			DATETIME
	,	BOOK_LAST_UPDATE_DATE
			DATETIME
	,	PUBLISHER_ID
			DECIMAL(6, 0)
			NOT NULL
			CONSTRAINT FK_PUBLISHERS__PUBLISHER_ID
				FOREIGN KEY REFERENCES TBUB_PUBLISHERS(PUBLISHER_ID)
	)
END

IF (NOT EXISTS(SELECT 1 FROM dbo.sysobjects WHERE ID = OBJECT_ID(N'dbo.TBUB_BOOKS_AUTHORS') AND OBJECTPROPERTY(ID, N'IsTable') = 1))
BEGIN
	CREATE TABLE TBUB_BOOKS_AUTHORS (
		BOOK_ISBN
			DECIMAL(13, 0)
			NOT NULL
			CONSTRAINT FK_BOOKS__BOOK_ISBN
				FOREIGN KEY REFERENCES TBUB_BOOKS(BOOK_ISBN)
	,	AUTHOR_ID
			DECIMAL(10, 0)
			NOT NULL
			CONSTRAINT FK_AUTHORS__AUTHOR_ID
				FOREIGN KEY REFERENCES TBUB_AUTHORS(AUTHOR_ID)

	,	CONSTRAINT PK_BOOKS_AUTHORS__BOOK_ISBN__AUTHOR_ID
			PRIMARY KEY CLUSTERED(BOOK_ISBN, AUTHOR_ID)
			
	)
END
GO

/*
 * CREATE INDEXES.
 */
IF (NOT EXISTS(SELECT 1 FROM sys.indexes WHERE NAME = N'IX_BOOKS__BOOK_TITLE' AND OBJECT_ID = OBJECT_ID(N'dbo.TBUB_BOOKS')))
BEGIN
	CREATE INDEX IX_BOOKS__BOOK_TITLE ON TBUB_BOOKS(BOOK_TITLE)
END

IF (NOT EXISTS(SELECT 1 FROM sys.indexes WHERE NAME = N'IX_BOOKS__PUBLISHER_ID' AND OBJECT_ID = OBJECT_ID(N'dbo.TBUB_BOOKS')))
BEGIN
	CREATE INDEX IX_BOOKS__PUBLISHER_ID ON dbo.TBUB_BOOKS(PUBLISHER_ID)
END
GO